// 模拟数据生成工具
const MockData = {
    // 生成随机ID
    generateId() {
        return Math.random().toString(36).substr(2, 9);
    },

    // 生成随机日期
    generateDate(daysBack = 30) {
        const date = new Date();
        date.setDate(date.getDate() - Math.floor(Math.random() * daysBack));
        return date.toISOString().split('T')[0];
    },

    // 生成随机状态
    generateStatus(statuses) {
        return statuses[Math.floor(Math.random() * statuses.length)];
    },

    // 测试计划数据
    testPlans: [
        {
            id: 'TP001',
            name: '电商平台核心功能测试',
            description: '包含用户注册登录、商品浏览购买、支付等核心功能的测试计划',
            version: 'v2.1.0',
            status: 'active',
            priority: 'high',
            startDate: '2024-01-15',
            endDate: '2024-02-15',
            progress: 75,
            testCases: 45,
            passed: 32,
            failed: 8,
            blocked: 3,
            notExecuted: 2,
            owner: '张测试',
            environment: '测试环境'
        },
        {
            id: 'TP002',
            name: '移动端APP兼容性测试',
            description: '针对iOS和Android平台的兼容性测试，确保应用在不同设备上正常运行',
            version: 'v1.8.3',
            status: 'in_progress',
            priority: 'medium',
            startDate: '2024-01-20',
            endDate: '2024-02-10',
            progress: 45,
            testCases: 38,
            passed: 15,
            failed: 5,
            blocked: 2,
            notExecuted: 16,
            owner: '李移动',
            environment: '移动测试环境'
        },
        {
            id: 'TP003',
            name: 'API接口安全测试',
            description: '对所有API接口进行安全性测试，包括权限验证、数据加密等',
            version: 'v3.0.0',
            status: 'completed',
            priority: 'high',
            startDate: '2024-01-01',
            endDate: '2024-01-25',
            progress: 100,
            testCases: 52,
            passed: 48,
            failed: 3,
            blocked: 0,
            notExecuted: 1,
            owner: '王安全',
            environment: '安全测试环境'
        },
        {
            id: 'TP004',
            name: '性能压力测试计划',
            description: '系统在高并发情况下的性能表现测试，包括响应时间和吞吐量',
            version: 'v2.3.1',
            status: 'draft',
            priority: 'high',
            startDate: '2024-02-01',
            endDate: '2024-02-20',
            progress: 0,
            testCases: 28,
            passed: 0,
            failed: 0,
            blocked: 0,
            notExecuted: 28,
            owner: '刘性能',
            environment: '性能测试环境'
        },
        {
            id: 'TP005',
            name: '数据库备份恢复测试',
            description: '验证数据库备份和恢复功能的正确性和完整性',
            version: 'v1.5.0',
            status: 'on_hold',
            priority: 'medium',
            startDate: '2024-01-28',
            endDate: '2024-02-12',
            progress: 20,
            testCases: 22,
            passed: 4,
            failed: 1,
            blocked: 1,
            notExecuted: 16,
            owner: '陈数据',
            environment: '数据库测试环境'
        },
        {
            id: 'TP006',
            name: '用户体验测试计划',
            description: '针对用户界面和交互体验的全面测试',
            version: 'v2.0.5',
            status: 'active',
            priority: 'medium',
            startDate: '2024-01-25',
            endDate: '2024-02-25',
            progress: 60,
            testCases: 35,
            passed: 18,
            failed: 4,
            blocked: 2,
            notExecuted: 11,
            owner: '吴体验',
            environment: 'UI测试环境'
        },
        {
            id: 'TP007',
            name: '第三方集成测试',
            description: '验证与第三方服务的集成功能，包括支付、物流等',
            version: 'v1.9.2',
            status: 'in_progress',
            priority: 'high',
            startDate: '2024-01-30',
            endDate: '2024-02-18',
            progress: 35,
            testCases: 30,
            passed: 8,
            failed: 3,
            blocked: 1,
            notExecuted: 18,
            owner: '赵集成',
            environment: '集成测试环境'
        },
        {
            id: 'TP008',
            name: '多语言本地化测试',
            description: '验证系统在不同语言环境下的显示和功能正确性',
            version: 'v2.2.0',
            status: 'completed',
            priority: 'low',
            startDate: '2024-01-10',
            endDate: '2024-01-30',
            progress: 100,
            testCases: 25,
            passed: 23,
            failed: 1,
            blocked: 0,
            notExecuted: 1,
            owner: '孙本地',
            environment: '本地化测试环境'
        },
        {
            id: 'TP009',
            name: '浏览器兼容性测试',
            description: '在不同浏览器中验证Web应用的兼容性',
            version: 'v3.1.0',
            status: 'draft',
            priority: 'medium',
            startDate: '2024-02-05',
            endDate: '2024-02-22',
            progress: 0,
            testCases: 40,
            passed: 0,
            failed: 0,
            blocked: 0,
            notExecuted: 40,
            owner: '郑浏览',
            environment: '兼容性测试环境'
        },
        {
            id: 'TP010',
            name: '系统升级回归测试',
            description: '系统版本升级后的回归测试，确保原有功能正常',
            version: 'v2.4.0',
            status: 'active',
            priority: 'high',
            startDate: '2024-02-01',
            endDate: '2024-02-28',
            progress: 25,
            testCases: 60,
            passed: 12,
            failed: 2,
            blocked: 1,
            notExecuted: 45,
            owner: '周回归',
            environment: '回归测试环境'
        }
    ],

    // 测试用例数据
    testCases: [
        {
            id: 'TC001',
            title: '用户注册功能验证',
            description: '验证用户注册流程的完整性和数据验证',
            module: '用户管理',
            priority: 'high',
            type: 'functional',
            status: 'passed',
            assignee: '张测试员',
            precondition: '系统正常运行，数据库连接正常',
            steps: [
                '1. 打开注册页面',
                '2. 输入用户信息',
                '3. 点击注册按钮',
                '4. 验证注册结果'
            ],
            expectedResult: '用户成功注册并收到确认信息',
            actualResult: '注册成功，符合预期',
            executionTime: '2024-01-15 14:30:00',
            tags: ['registration', 'user', 'validation'],
            automationStatus: 'automated',
            lastExecuted: '2024-01-20',
            executionCount: 5
        },
        {
            id: 'TC002',
            title: '用户登录功能测试',
            description: '测试用户登录的各种场景，包括正确和错误的凭据',
            module: '用户管理',
            priority: 'high',
            type: 'functional',
            status: 'failed',
            assignee: '李测试员',
            precondition: '用户已注册，系统运行正常',
            steps: [
                '1. 打开登录页面',
                '2. 输入用户名和密码',
                '3. 点击登录按钮',
                '4. 验证登录结果'
            ],
            expectedResult: '用户成功登录并跳转到主页',
            actualResult: '登录失败，出现500错误',
            executionTime: '2024-01-16 10:15:00',
            tags: ['login', 'authentication', 'security'],
            automationStatus: 'manual',
            lastExecuted: '2024-01-21',
            executionCount: 3
        },
        {
            id: 'TC003',
            title: '商品搜索功能测试',
            description: '验证商品搜索的准确性和响应时间',
            module: '商品管理',
            priority: 'medium',
            type: 'functional',
            status: 'passed',
            assignee: '王测试员',
            precondition: '商品数据已初始化',
            steps: [
                '1. 在搜索框输入关键词',
                '2. 点击搜索按钮',
                '3. 查看搜索结果',
                '4. 验证结果准确性'
            ],
            expectedResult: '显示相关商品列表',
            actualResult: '搜索结果准确，响应时间正常',
            executionTime: '2024-01-17 16:20:00',
            tags: ['search', 'product', 'performance'],
            automationStatus: 'automated',
            lastExecuted: '2024-01-22',
            executionCount: 8
        },
        {
            id: 'TC004',
            title: '购物车添加商品测试',
            description: '测试将商品添加到购物车的功能',
            module: '购物车',
            priority: 'high',
            type: 'functional',
            status: 'blocked',
            assignee: '赵测试员',
            precondition: '用户已登录，商品页面正常显示',
            steps: [
                '1. 选择商品',
                '2. 点击加入购物车',
                '3. 查看购物车',
                '4. 验证商品已添加'
            ],
            expectedResult: '商品成功添加到购物车',
            actualResult: '功能被阻塞，依赖模块未完成',
            executionTime: '2024-01-18 11:45:00',
            tags: ['cart', 'product', 'add'],
            automationStatus: 'pending',
            lastExecuted: '2024-01-19',
            executionCount: 1
        },
        {
            id: 'TC005',
            title: '订单结算功能测试',
            description: '验证订单结算流程的完整性',
            module: '订单管理',
            priority: 'high',
            type: 'functional',
            status: 'passed',
            assignee: '钱测试员',
            precondition: '购物车中有商品，用户已登录',
            steps: [
                '1. 进入购物车页面',
                '2. 点击结算按钮',
                '3. 填写收货信息',
                '4. 选择支付方式',
                '5. 确认订单'
            ],
            expectedResult: '订单创建成功，生成订单号',
            actualResult: '订单创建成功，功能正常',
            executionTime: '2024-01-19 13:10:00',
            tags: ['order', 'checkout', 'payment'],
            automationStatus: 'automated',
            lastExecuted: '2024-01-23',
            executionCount: 6
        },
        {
            id: 'TC006',
            title: '支付功能集成测试',
            description: '测试与第三方支付平台的集成',
            module: '支付系统',
            priority: 'high',
            type: 'integration',
            status: 'not_executed',
            assignee: '孙测试员',
            precondition: '订单已生成，支付环境配置正确',
            steps: [
                '1. 选择支付方式',
                '2. 跳转到支付页面',
                '3. 完成支付操作',
                '4. 返回系统验证结果'
            ],
            expectedResult: '支付成功，订单状态更新',
            actualResult: '尚未执行',
            executionTime: null,
            tags: ['payment', 'integration', 'third-party'],
            automationStatus: 'manual',
            lastExecuted: null,
            executionCount: 0
        },
        {
            id: 'TC007',
            title: '移动端响应式布局测试',
            description: '验证页面在不同移动设备上的显示效果',
            module: 'UI界面',
            priority: 'medium',
            type: 'ui',
            status: 'passed',
            assignee: '李移动测试',
            precondition: '移动设备或模拟器可用',
            steps: [
                '1. 在不同屏幕尺寸下打开页面',
                '2. 检查布局适应性',
                '3. 验证触摸操作',
                '4. 测试横竖屏切换'
            ],
            expectedResult: '页面在各设备上正常显示和操作',
            actualResult: '响应式布局正常，用户体验良好',
            executionTime: '2024-01-20 15:30:00',
            tags: ['mobile', 'responsive', 'ui'],
            automationStatus: 'manual',
            lastExecuted: '2024-01-24',
            executionCount: 4
        },
        {
            id: 'TC008',
            title: 'API接口安全性测试',
            description: '测试API接口的安全性，包括权限验证',
            module: 'API接口',
            priority: 'high',
            type: 'security',
            status: 'failed',
            assignee: '王安全测试',
            precondition: 'API接口正常运行',
            steps: [
                '1. 测试未授权访问',
                '2. 测试SQL注入攻击',
                '3. 测试XSS攻击',
                '4. 验证数据加密'
            ],
            expectedResult: '所有安全测试通过，无漏洞',
            actualResult: '发现权限验证缺陷',
            executionTime: '2024-01-21 09:45:00',
            tags: ['api', 'security', 'vulnerability'],
            automationStatus: 'automated',
            lastExecuted: '2024-01-25',
            executionCount: 3
        },
        {
            id: 'TC009',
            title: '系统性能压力测试',
            description: '测试系统在高并发下的性能表现',
            module: '系统性能',
            priority: 'high',
            type: 'performance',
            status: 'passed',
            assignee: '刘性能测试',
            precondition: '系统部署完成，性能测试工具就绪',
            steps: [
                '1. 配置并发用户数',
                '2. 启动压力测试',
                '3. 监控系统资源',
                '4. 分析测试结果'
            ],
            expectedResult: '系统在指定并发下稳定运行',
            actualResult: '系统性能满足要求',
            executionTime: '2024-01-22 14:00:00',
            tags: ['performance', 'load', 'stress'],
            automationStatus: 'automated',
            lastExecuted: '2024-01-26',
            executionCount: 2
        },
        {
            id: 'TC010',
            title: '数据备份恢复测试',
            description: '验证数据备份和恢复功能的完整性',
            module: '数据管理',
            priority: 'medium',
            type: 'functional',
            status: 'blocked',
            assignee: '陈数据测试',
            precondition: '数据库正常运行，备份工具可用',
            steps: [
                '1. 执行数据备份',
                '2. 模拟数据丢失',
                '3. 执行数据恢复',
                '4. 验证数据完整性'
            ],
            expectedResult: '数据完整恢复，无丢失',
            actualResult: '测试环境问题，暂时阻塞',
            executionTime: '2024-01-23 10:20:00',
            tags: ['database', 'backup', 'recovery'],
            automationStatus: 'manual',
            lastExecuted: '2024-01-23',
            executionCount: 1
        }
    ],

    // 缺陷数据
    defects: [
        {
            id: 'BUG001',
            title: '用户登录时出现500内部服务器错误',
            description: '在用户尝试登录时，系统返回500内部服务器错误，导致无法正常登录',
            severity: 'critical',
            priority: 'urgent',
            status: 'open',
            type: 'functional',
            assignee: '开发团队A',
            reporter: '李测试员',
            module: '用户管理',
            environment: '测试环境',
            browser: 'Chrome 118',
            os: 'Windows 11',
            createdDate: '2024-01-16',
            lastUpdated: '2024-01-17',
            dueDate: '2024-01-20',
            resolution: null,
            testCase: 'TC002',
            attachments: ['error_screenshot.png', 'server_log.txt'],
            tags: ['login', 'server-error', 'blocking'],
            reproducible: true,
            workaround: '清除浏览器缓存后重试'
        },
        {
            id: 'BUG002',
            title: 'API接口权限验证缺陷',
            description: '某些API接口缺少权限验证，普通用户可以访问管理员权限的接口',
            severity: 'high',
            priority: 'high',
            status: 'in_progress',
            type: 'security',
            assignee: '安全开发组',
            reporter: '王安全测试',
            module: 'API接口',
            environment: '测试环境',
            browser: 'N/A',
            os: 'Linux',
            createdDate: '2024-01-21',
            lastUpdated: '2024-01-24',
            dueDate: '2024-01-28',
            resolution: null,
            testCase: 'TC008',
            attachments: ['api_test_report.pdf'],
            tags: ['security', 'api', 'permission'],
            reproducible: true,
            workaround: '暂时限制API访问'
        },
        {
            id: 'BUG003',
            title: '购物车商品数量显示错误',
            description: '添加商品到购物车后，显示的数量与实际添加的数量不符',
            severity: 'medium',
            priority: 'medium',
            status: 'resolved',
            type: 'functional',
            assignee: '前端开发组',
            reporter: '赵测试员',
            module: '购物车',
            environment: '测试环境',
            browser: 'Firefox 119',
            os: 'macOS 14',
            createdDate: '2024-01-18',
            lastUpdated: '2024-01-25',
            dueDate: '2024-01-22',
            resolution: 'fixed',
            testCase: 'TC004',
            attachments: ['cart_bug_video.mp4'],
            tags: ['cart', 'quantity', 'display'],
            reproducible: false,
            workaround: '刷新页面可显示正确数量'
        },
        {
            id: 'BUG004',
            title: '移动端页面布局错乱',
            description: '在小屏幕设备上，页面元素重叠，影响用户体验',
            severity: 'medium',
            priority: 'medium',
            status: 'open',
            type: 'ui',
            assignee: 'UI开发组',
            reporter: '李移动测试',
            module: 'UI界面',
            environment: '移动测试环境',
            browser: 'Safari Mobile',
            os: 'iOS 17',
            createdDate: '2024-01-20',
            lastUpdated: '2024-01-20',
            dueDate: '2024-01-27',
            resolution: null,
            testCase: 'TC007',
            attachments: ['mobile_layout_issue.png'],
            tags: ['mobile', 'layout', 'responsive'],
            reproducible: true,
            workaround: '横屏使用暂时正常'
        },
        {
            id: 'BUG005',
            title: '系统性能在高并发下响应缓慢',
            description: '当并发用户数超过1000时，系统响应时间明显增加',
            severity: 'high',
            priority: 'high',
            status: 'open',
            type: 'performance',
            assignee: '性能优化组',
            reporter: '刘性能测试',
            module: '系统性能',
            environment: '性能测试环境',
            browser: 'N/A',
            os: 'Linux',
            createdDate: '2024-01-22',
            lastUpdated: '2024-01-23',
            dueDate: '2024-01-30',
            resolution: null,
            testCase: 'TC009',
            attachments: ['performance_report.xlsx'],
            tags: ['performance', 'load', 'response-time'],
            reproducible: true,
            workaround: '限制并发用户数'
        },
        {
            id: 'BUG006',
            title: '搜索结果分页功能异常',
            description: '在搜索结果页面点击分页按钮时，返回错误的结果集',
            severity: 'medium',
            priority: 'low',
            status: 'closed',
            type: 'functional',
            assignee: '后端开发组',
            reporter: '王测试员',
            module: '商品管理',
            environment: '测试环境',
            browser: 'Chrome 118',
            os: 'Windows 10',
            createdDate: '2024-01-17',
            lastUpdated: '2024-01-26',
            dueDate: '2024-01-24',
            resolution: 'fixed',
            testCase: 'TC003',
            attachments: ['search_pagination_bug.gif'],
            tags: ['search', 'pagination', 'results'],
            reproducible: false,
            workaround: '手动输入页码'
        },
        {
            id: 'BUG007',
            title: '订单状态更新延迟',
            description: '支付成功后，订单状态未及时更新，用户看到的仍是未支付状态',
            severity: 'high',
            priority: 'high',
            status: 'in_progress',
            type: 'functional',
            assignee: '订单管理组',
            reporter: '钱测试员',
            module: '订单管理',
            environment: '测试环境',
            browser: 'Edge 118',
            os: 'Windows 11',
            createdDate: '2024-01-19',
            lastUpdated: '2024-01-25',
            dueDate: '2024-01-26',
            resolution: null,
            testCase: 'TC005',
            attachments: ['order_status_log.txt'],
            tags: ['order', 'status', 'payment'],
            reproducible: true,
            workaround: '刷新页面或等待5分钟'
        },
        {
            id: 'BUG008',
            title: '数据库连接池泄漏',
            description: '长时间运行后，数据库连接池出现泄漏，影响系统稳定性',
            severity: 'critical',
            priority: 'urgent',
            status: 'open',
            type: 'system',
            assignee: '系统架构组',
            reporter: '陈数据测试',
            module: '数据管理',
            environment: '测试环境',
            browser: 'N/A',
            os: 'Linux',
            createdDate: '2024-01-23',
            lastUpdated: '2024-01-24',
            dueDate: '2024-01-27',
            resolution: null,
            testCase: 'TC010',
            attachments: ['db_connection_monitor.png'],
            tags: ['database', 'connection-pool', 'memory-leak'],
            reproducible: true,
            workaround: '定期重启应用服务'
        },
        {
            id: 'BUG009',
            title: '文件上传功能限制不生效',
            description: '设置的文件大小限制不生效，允许上传超出限制的文件',
            severity: 'medium',
            priority: 'medium',
            status: 'resolved',
            type: 'functional',
            assignee: '文件管理组',
            reporter: '周测试员',
            module: '文件管理',
            environment: '测试环境',
            browser: 'Safari 16',
            os: 'macOS 13',
            createdDate: '2024-01-15',
            lastUpdated: '2024-01-22',
            dueDate: '2024-01-20',
            resolution: 'fixed',
            testCase: null,
            attachments: ['file_upload_test.zip'],
            tags: ['file-upload', 'validation', 'size-limit'],
            reproducible: false,
            workaround: '手动检查文件大小'
        },
        {
            id: 'BUG010',
            title: '邮件通知发送失败',
            description: '用户注册成功后，确认邮件发送失败，影响账户激活',
            severity: 'high',
            priority: 'medium',
            status: 'open',
            type: 'integration',
            assignee: '通知服务组',
            reporter: '张测试员',
            module: '用户管理',
            environment: '测试环境',
            browser: 'N/A',
            os: 'Linux',
            createdDate: '2024-01-15',
            lastUpdated: '2024-01-16',
            dueDate: '2024-01-29',
            resolution: null,
            testCase: 'TC001',
            attachments: ['email_error_log.txt'],
            tags: ['email', 'notification', 'registration'],
            reproducible: true,
            workaround: '管理员手动激活账户'
        }
    ],

    // 自动化测试数据
    automationTests: [
        {
            id: 'AT001',
            name: '用户注册登录自动化测试套件',
            description: '自动化测试用户注册和登录流程',
            framework: 'Selenium',
            language: 'Java',
            status: 'active',
            lastRun: '2024-01-26 08:30:00',
            duration: '5分32秒',
            passed: 8,
            failed: 1,
            skipped: 0,
            passRate: 89,
            environment: '自动化测试环境',
            schedule: 'daily',
            author: '自动化团队A',
            tags: ['smoke', 'user-management', 'critical-path']
        },
        {
            id: 'AT002',
            name: 'API接口回归测试',
            description: '所有REST API接口的自动化回归测试',
            framework: 'RestAssured',
            language: 'Java',
            status: 'active',
            lastRun: '2024-01-26 09:15:00',
            duration: '12分18秒',
            passed: 45,
            failed: 3,
            skipped: 2,
            passRate: 90,
            environment: 'API测试环境',
            schedule: 'nightly',
            author: '自动化团队B',
            tags: ['api', 'regression', 'backend']
        },
        {
            id: 'AT003',
            name: '购物流程端到端测试',
            description: '完整的购物流程自动化测试',
            framework: 'Cypress',
            language: 'JavaScript',
            status: 'active',
            lastRun: '2024-01-25 22:00:00',
            duration: '18分45秒',
            passed: 12,
            failed: 2,
            skipped: 1,
            passRate: 80,
            environment: 'E2E测试环境',
            schedule: 'nightly',
            author: '前端自动化组',
            tags: ['e2e', 'shopping', 'critical-path']
        },
        {
            id: 'AT004',
            name: '移动端UI自动化测试',
            description: '移动应用UI元素和交互的自动化测试',
            framework: 'Appium',
            language: 'Python',
            status: 'active',
            lastRun: '2024-01-26 07:45:00',
            duration: '25分12秒',
            passed: 20,
            failed: 5,
            skipped: 0,
            passRate: 80,
            environment: '移动测试环境',
            schedule: 'weekly',
            author: '移动自动化组',
            tags: ['mobile', 'ui', 'android', 'ios']
        },
        {
            id: 'AT005',
            name: '性能监控自动化测试',
            description: '系统关键指标的性能监控测试',
            framework: 'JMeter',
            language: 'Groovy',
            status: 'inactive',
            lastRun: '2024-01-22 14:00:00',
            duration: '45分30秒',
            passed: 8,
            failed: 0,
            skipped: 2,
            passRate: 100,
            environment: '性能测试环境',
            schedule: 'weekly',
            author: '性能测试组',
            tags: ['performance', 'monitoring', 'load']
        },
        {
            id: 'AT006',
            name: '安全扫描自动化测试',
            description: '安全漏洞扫描和检测的自动化测试',
            framework: 'OWASP ZAP',
            language: 'Python',
            status: 'active',
            lastRun: '2024-01-25 23:30:00',
            duration: '35分22秒',
            passed: 15,
            failed: 3,
            skipped: 0,
            passRate: 83,
            environment: '安全测试环境',
            schedule: 'weekly',
            author: '安全测试组',
            tags: ['security', 'vulnerability', 'scan']
        },
        {
            id: 'AT007',
            name: '数据库集成测试',
            description: '数据库操作和数据一致性的自动化测试',
            framework: 'TestNG',
            language: 'Java',
            status: 'active',
            lastRun: '2024-01-26 06:00:00',
            duration: '8分55秒',
            passed: 22,
            failed: 1,
            skipped: 0,
            passRate: 96,
            environment: '数据库测试环境',
            schedule: 'daily',
            author: '数据库测试组',
            tags: ['database', 'integration', 'data-consistency']
        },
        {
            id: 'AT008',
            name: '跨浏览器兼容性测试',
            description: '多种浏览器的兼容性自动化测试',
            framework: 'Selenium Grid',
            language: 'C#',
            status: 'maintenance',
            lastRun: '2024-01-24 20:15:00',
            duration: '32分08秒',
            passed: 35,
            failed: 8,
            skipped: 2,
            passRate: 78,
            environment: '兼容性测试环境',
            schedule: 'weekly',
            author: '兼容性测试组',
            tags: ['cross-browser', 'compatibility', 'selenium-grid']
        },
        {
            id: 'AT009',
            name: '微服务集成测试',
            description: '微服务之间的集成和通信测试',
            framework: 'SpringBoot Test',
            language: 'Java',
            status: 'active',
            lastRun: '2024-01-26 10:30:00',
            duration: '15分42秒',
            passed: 18,
            failed: 2,
            skipped: 1,
            passRate: 86,
            environment: '集成测试环境',
            schedule: 'daily',
            author: '微服务测试组',
            tags: ['microservices', 'integration', 'api']
        },
        {
            id: 'AT010',
            name: '持续集成烟雾测试',
            description: 'CI/CD流程中的快速烟雾测试',
            framework: 'Pytest',
            language: 'Python',
            status: 'active',
            lastRun: '2024-01-26 11:45:00',
            duration: '3分28秒',
            passed: 12,
            failed: 0,
            skipped: 0,
            passRate: 100,
            environment: 'CI环境',
            schedule: 'on-commit',
            author: 'DevOps团队',
            tags: ['smoke', 'ci-cd', 'fast']
        }
    ],

    // 测试执行记录
    testExecutions: [
        {
            id: 'TE001',
            testCase: 'TC001',
            executedBy: '张测试员',
            executionDate: '2024-01-26',
            executionTime: '14:30:00',
            status: 'passed',
            duration: '3分15秒',
            browser: 'Chrome 118',
            os: 'Windows 11',
            environment: '测试环境',
            notes: '测试通过，用户注册流程正常',
            screenshots: ['registration_success.png'],
            defects: []
        },
        {
            id: 'TE002',
            testCase: 'TC002',
            executedBy: '李测试员',
            executionDate: '2024-01-26',
            executionTime: '15:45:00',
            status: 'failed',
            duration: '2分30秒',
            browser: 'Chrome 118',
            os: 'Windows 11',
            environment: '测试环境',
            notes: '登录失败，服务器返回500错误',
            screenshots: ['login_error.png'],
            defects: ['BUG001']
        },
        {
            id: 'TE003',
            testCase: 'TC003',
            executedBy: '王测试员',
            executionDate: '2024-01-26',
            executionTime: '16:20:00',
            status: 'passed',
            duration: '4分10秒',
            browser: 'Firefox 119',
            os: 'macOS 14',
            environment: '测试环境',
            notes: '搜索功能正常，结果准确',
            screenshots: ['search_results.png'],
            defects: []
        },
        {
            id: 'TE004',
            testCase: 'TC004',
            executedBy: '赵测试员',
            executionDate: '2024-01-25',
            executionTime: '10:15:00',
            status: 'blocked',
            duration: '1分45秒',
            browser: 'Chrome 118',
            os: 'Windows 10',
            environment: '测试环境',
            notes: '依赖功能未完成，无法执行',
            screenshots: [],
            defects: []
        },
        {
            id: 'TE005',
            testCase: 'TC005',
            executedBy: '钱测试员',
            executionDate: '2024-01-26',
            executionTime: '11:30:00',
            status: 'passed',
            duration: '6分25秒',
            browser: 'Edge 118',
            os: 'Windows 11',
            environment: '测试环境',
            notes: '订单创建成功，流程完整',
            screenshots: ['order_created.png'],
            defects: []
        },
        {
            id: 'TE006',
            testCase: 'TC008',
            executedBy: '王安全测试',
            executionDate: '2024-01-25',
            executionTime: '09:45:00',
            status: 'failed',
            duration: '8分15秒',
            browser: 'N/A',
            os: 'Linux',
            environment: '安全测试环境',
            notes: '发现权限验证漏洞',
            screenshots: ['security_issue.png'],
            defects: ['BUG002']
        },
        {
            id: 'TE007',
            testCase: 'TC009',
            executedBy: '刘性能测试',
            executionDate: '2024-01-26',
            executionTime: '14:00:00',
            status: 'passed',
            duration: '30分00秒',
            browser: 'N/A',
            os: 'Linux',
            environment: '性能测试环境',
            notes: '性能测试通过，满足要求',
            screenshots: ['performance_report.png'],
            defects: []
        },
        {
            id: 'TE008',
            testCase: 'TC007',
            executedBy: '李移动测试',
            executionDate: '2024-01-24',
            executionTime: '15:30:00',
            status: 'passed',
            duration: '10分20秒',
            browser: 'Safari Mobile',
            os: 'iOS 17',
            environment: '移动测试环境',
            notes: '移动端显示正常',
            screenshots: ['mobile_layout.png'],
            defects: []
        },
        {
            id: 'TE009',
            testCase: 'TC010',
            executedBy: '陈数据测试',
            executionDate: '2024-01-23',
            executionTime: '10:20:00',
            status: 'blocked',
            duration: '5分00秒',
            browser: 'N/A',
            os: 'Linux',
            environment: '数据库测试环境',
            notes: '环境配置问题，暂时无法执行',
            screenshots: [],
            defects: []
        },
        {
            id: 'TE010',
            testCase: 'TC006',
            executedBy: '孙测试员',
            executionDate: '2024-01-22',
            executionTime: '13:10:00',
            status: 'not_executed',
            duration: null,
            browser: 'Chrome 118',
            os: 'Windows 11',
            environment: '测试环境',
            notes: '等待支付环境配置',
            screenshots: [],
            defects: []
        }
    ],

    // 测试报告数据
    testReports: [
        {
            id: 'TR001',
            name: '电商平台2024年1月测试报告',
            type: 'comprehensive',
            period: '2024-01-01 至 2024-01-31',
            status: 'published',
            author: '测试经理',
            createdDate: '2024-01-26',
            testPlans: 5,
            totalTestCases: 156,
            executedCases: 134,
            passedCases: 98,
            failedCases: 28,
            blockedCases: 8,
            passRate: 73.1,
            defectsFound: 42,
            criticalDefects: 5,
            highDefects: 12,
            mediumDefects: 18,
            lowDefects: 7,
            summary: '本月测试覆盖了主要功能模块，发现了一些关键问题需要优先解决。',
            recommendations: '建议加强API安全测试和性能测试。',
            coverage: 85.6
        },
        {
            id: 'TR002',
            name: '移动端APP测试周报',
            type: 'weekly',
            period: '2024-01-22 至 2024-01-26',
            status: 'draft',
            author: '移动测试组',
            createdDate: '2024-01-26',
            testPlans: 2,
            totalTestCases: 38,
            executedCases: 32,
            passedCases: 24,
            failedCases: 6,
            blockedCases: 2,
            passRate: 75.0,
            defectsFound: 8,
            criticalDefects: 1,
            highDefects: 2,
            mediumDefects: 4,
            lowDefects: 1,
            summary: '移动端测试进展良好，主要问题集中在UI适配方面。',
            recommendations: '建议增加更多设备型号的测试覆盖。',
            coverage: 78.9
        },
        {
            id: 'TR003',
            name: 'API接口安全测试报告',
            type: 'security',
            period: '2024-01-15 至 2024-01-25',
            status: 'published',
            author: '安全测试组',
            createdDate: '2024-01-25',
            testPlans: 1,
            totalTestCases: 52,
            executedCases: 52,
            passedCases: 35,
            failedCases: 15,
            blockedCases: 2,
            passRate: 67.3,
            defectsFound: 18,
            criticalDefects: 3,
            highDefects: 5,
            mediumDefects: 7,
            lowDefects: 3,
            summary: '安全测试发现了多个严重漏洞，需要紧急修复。',
            recommendations: '强烈建议立即修复所有高危和严重漏洞。',
            coverage: 100.0
        },
        {
            id: 'TR004',
            name: '性能测试分析报告',
            type: 'performance',
            period: '2024-01-20 至 2024-01-26',
            status: 'published',
            author: '性能测试组',
            createdDate: '2024-01-26',
            testPlans: 1,
            totalTestCases: 28,
            executedCases: 25,
            passedCases: 20,
            failedCases: 3,
            blockedCases: 2,
            passRate: 80.0,
            defectsFound: 5,
            criticalDefects: 1,
            highDefects: 2,
            mediumDefects: 2,
            lowDefects: 0,
            summary: '系统在正常负载下性能良好，但高并发时存在问题。',
            recommendations: '优化数据库查询和增加缓存机制。',
            coverage: 89.3
        },
        {
            id: 'TR005',
            name: '自动化测试执行报告',
            type: 'automation',
            period: '2024-01-26',
            status: 'published',
            author: '自动化测试组',
            createdDate: '2024-01-26',
            testPlans: 8,
            totalTestCases: 187,
            executedCases: 187,
            passedCases: 158,
            failedCases: 25,
            blockedCases: 4,
            passRate: 84.5,
            defectsFound: 12,
            criticalDefects: 2,
            highDefects: 4,
            mediumDefects: 5,
            lowDefects: 1,
            summary: '自动化测试运行稳定，通过率良好。',
            recommendations: '继续扩大自动化测试覆盖范围。',
            coverage: 92.1
        }
    ],

    // 测试环境数据
    testEnvironments: [
        {
            id: 'ENV001',
            name: '开发环境',
            url: 'https://dev.example.com',
            status: 'active',
            type: 'development',
            version: 'v2.1.0-dev',
            lastUpdated: '2024-01-26',
            maintainer: '开发团队',
            resources: {
                cpu: '4 cores',
                memory: '8GB',
                storage: '100GB'
            },
            services: ['web', 'api', 'database', 'redis'],
            description: '开发人员日常开发使用的环境'
        },
        {
            id: 'ENV002',
            name: '测试环境',
            url: 'https://test.example.com',
            status: 'active',
            type: 'testing',
            version: 'v2.1.0-rc1',
            lastUpdated: '2024-01-25',
            maintainer: '测试团队',
            resources: {
                cpu: '8 cores',
                memory: '16GB',
                storage: '200GB'
            },
            services: ['web', 'api', 'database', 'redis', 'elasticsearch'],
            description: '功能测试和集成测试专用环境'
        },
        {
            id: 'ENV003',
            name: '性能测试环境',
            url: 'https://perf.example.com',
            status: 'active',
            type: 'performance',
            version: 'v2.1.0-rc1',
            lastUpdated: '2024-01-24',
            maintainer: '性能测试组',
            resources: {
                cpu: '16 cores',
                memory: '32GB',
                storage: '500GB'
            },
            services: ['web', 'api', 'database', 'redis', 'monitoring'],
            description: '专门用于性能和压力测试的高配置环境'
        },
        {
            id: 'ENV004',
            name: '安全测试环境',
            url: 'https://security.example.com',
            status: 'maintenance',
            type: 'security',
            version: 'v2.0.8',
            lastUpdated: '2024-01-20',
            maintainer: '安全测试组',
            resources: {
                cpu: '4 cores',
                memory: '8GB',
                storage: '150GB'
            },
            services: ['web', 'api', 'database', 'security-scanner'],
            description: '隔离的安全测试环境，用于漏洞扫描'
        },
        {
            id: 'ENV005',
            name: '预生产环境',
            url: 'https://staging.example.com',
            status: 'active',
            type: 'staging',
            version: 'v2.1.0-rc2',
            lastUpdated: '2024-01-26',
            maintainer: 'DevOps团队',
            resources: {
                cpu: '12 cores',
                memory: '24GB',
                storage: '300GB'
            },
            services: ['web', 'api', 'database', 'redis', 'monitoring', 'logging'],
            description: '与生产环境配置相同的预发布环境'
        }
    ],

    // 用户和团队数据
    users: [
        {
            id: 'U001',
            name: '张测试',
            email: 'zhang.test@example.com',
            role: 'test_manager',
            department: '质量保证',
            skills: ['测试管理', '测试计划', '团队协调'],
            activeProjects: ['TP001', 'TP010'],
            joinDate: '2023-06-15'
        },
        {
            id: 'U002',
            name: '李测试员',
            email: 'li.tester@example.com',
            role: 'senior_tester',
            department: '质量保证',
            skills: ['功能测试', '自动化测试', 'API测试'],
            activeProjects: ['TP001', 'TP002'],
            joinDate: '2023-08-20'
        },
        {
            id: 'U003',
            name: '王安全测试',
            email: 'wang.security@example.com',
            role: 'security_tester',
            department: '安全部门',
            skills: ['安全测试', '漏洞扫描', '渗透测试'],
            activeProjects: ['TP003'],
            joinDate: '2023-09-10'
        },
        {
            id: 'U004',
            name: '刘性能测试',
            email: 'liu.performance@example.com',
            role: 'performance_tester',
            department: '技术部门',
            skills: ['性能测试', 'JMeter', '系统监控'],
            activeProjects: ['TP004'],
            joinDate: '2023-07-05'
        },
        {
            id: 'U005',
            name: '陈数据测试',
            email: 'chen.data@example.com',
            role: 'data_tester',
            department: '数据部门',
            skills: ['数据测试', 'SQL', '数据库管理'],
            activeProjects: ['TP005'],
            joinDate: '2023-10-12'
        }
    ],

    // 统计数据生成方法
    generateStats() {
        return {
            overview: {
                totalTestPlans: this.testPlans.length,
                activeTestPlans: this.testPlans.filter(tp => tp.status === 'active').length,
                totalTestCases: this.testCases.length,
                executedCases: this.testCases.filter(tc => tc.status !== 'not_executed').length,
                passedCases: this.testCases.filter(tc => tc.status === 'passed').length,
                failedCases: this.testCases.filter(tc => tc.status === 'failed').length,
                totalDefects: this.defects.length,
                openDefects: this.defects.filter(d => d.status === 'open').length,
                criticalDefects: this.defects.filter(d => d.severity === 'critical').length,
                automationRate: Math.round((this.testCases.filter(tc => tc.automationStatus === 'automated').length / this.testCases.length) * 100)
            },
            trends: {
                testExecution: [
                    { date: '2024-01-20', passed: 45, failed: 8, blocked: 3 },
                    { date: '2024-01-21', passed: 52, failed: 6, blocked: 2 },
                    { date: '2024-01-22', passed: 48, failed: 9, blocked: 4 },
                    { date: '2024-01-23', passed: 55, failed: 5, blocked: 2 },
                    { date: '2024-01-24', passed: 61, failed: 4, blocked: 3 },
                    { date: '2024-01-25', passed: 58, failed: 7, blocked: 2 },
                    { date: '2024-01-26', passed: 63, failed: 3, blocked: 1 }
                ],
                defectTrend: [
                    { date: '2024-01-20', opened: 5, resolved: 3, closed: 2 },
                    { date: '2024-01-21', opened: 3, resolved: 4, closed: 1 },
                    { date: '2024-01-22', opened: 7, resolved: 2, closed: 3 },
                    { date: '2024-01-23', opened: 2, resolved: 5, closed: 2 },
                    { date: '2024-01-24', opened: 4, resolved: 3, closed: 4 },
                    { date: '2024-01-25', opened: 1, resolved: 6, closed: 1 },
                    { date: '2024-01-26', opened: 3, resolved: 2, closed: 2 }
                ]
            }
        };
    }
};

// 导出模拟数据
window.MockData = MockData;